crm/config/routes.rb
Rails.application.routes.draw do

root 'leads#index'

resources :leads do
  resources :call_logs
  resources :appointments
end

resources :accounts
resources :users, only: [:new, :create, :delete]
resources :sessions, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

crm/app/models/account.rb
class Account < ApplicationRecord

belongs_to :user
end

crm/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crm/app/models/appointment.rb
class Appointment < ApplicationRecord

  belongs_to :lead
end

crm/app/models/call_log.rb
class CallLog < ApplicationRecord

  belongs_to :lead
end

crm/app/models/lead.rb
class Lead < ApplicationRecord

  has_many :call_logs
  has_many :appointments
  belongs_to :user
end

crm/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :leads
  has_many :accounts
end

crm/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
  @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
    # @call_log = Call_Log.new()
  end

  def new
    @account = Account.new
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to accounts_path
    else
      render :new
    end
  end

  def update
    @account = Account.find(params[:id])

    if @account.update_attributes(account_params)
      redirect_to account_url(@account)
    else
      render :edit
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to accounts_url
  end

  private
  def account_params
    params.require(:account).permit(:first_name, :last_name, :phone_number, :notes)
  end
  end

crm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

crm/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :load_lead

  def index
  @appointments = Appointment.all
  end

  def show
    @appointment = Appointment.find(params[:id])
    @lead = Lead.find(params[:lead_id])
  end

  def new
    @appointment  = Appointment.new
    @lead = Lead.find(params[:lead_id])
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.lead = Lead.find(params[:lead_id])
    # @appointment.date = DateTime.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)

    if @appointment.save
      redirect_to lead_appointment_path(@lead,@appointment)
    else
      render :new
    end
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.lead = Lead.find(params[:lead_id])

    if  @appointment.update_attributes(appointment_params)
      redirect_to lead_appointment_path(@lead,@appointment)
    else
      render :edit
    end
  end

  def destroy
    @appointment  = Appointment.find(params[:id])
    @appointment.destroy
  end

  private
  def appointment_params
    params.require(:appointment).permit(:date, :lead_id, :time)
  end

  def load_lead
    @lead = Lead.find(params[:lead_id])
  end
end

crm/app/controllers/call_logs_controller.rb
class CallLogsController < ApplicationController

  before_action :load_lead

  def index
  @call_logs = CallLog.all
  end

  def show
    @call_log = CallLog.find(params[:id])
    @lead = Lead.find(params[:lead_id])
  end

  def new
    @call_log = CallLog.new
    @lead = Lead.find(params[:lead_id])
  end

  def edit
    @call_log = CallLog.find(params[:id])
  end

  def create

    @call_log = CallLog.new(call_log_params)
    @call_log.lead = Lead.find(params[:lead_id])

    if @call_log.save
      redirect_to lead_call_logs_path(@lead)
    else
      render :new
    end
  end

  def update
    @call_log = CallLog.find(params[:id])

    if @call_log.update_attributes(call_log_params)
      redirect_to lead_call_logs_url(@lead,@call_log)
    else
      render :edit
    end
  end

  def destroy
    @call_log = CallLog.find(params[:id])
    @call_log.destroy
  end

  private
  def call_log_params
    params.require(:call_log).permit(:note, :lead_id)
  end

  def load_lead
    @lead = Lead.find(params[:lead_id])
  end
end

crm/app/controllers/leads_controller.rb
class LeadsController < ApplicationController

def index
@leads = Lead.all
end

def show
  @lead = Lead.find(params[:id])
  @account = Account.new
end

def new
  @lead = Lead.new
  @account = Account.new
end

def edit
  @lead = Lead.find(params[:id])
end

def create
  @lead = Lead.new(lead_params)

  if @lead.save
    redirect_to leads_path
  else
    render :new
  end
end

def update
  @lead = Lead.find(params[:id])

  if @lead.update_attributes(lead_params)
    redirect_to lead_url(@lead)
  else
    render :edit
  end
end

def destroy
  @lead = Lead.find(params[:id])
  @lead.destroy
  redirect_to leads_url
end

private
def lead_params
  params.require(:lead).permit(:first_name, :last_name, :phone_number, :notes)
end

end

crm/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

crm/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to leads_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

crm/app/helpers/accounts_helper.rb
module AccountsHelper
end

crm/app/helpers/application_helper.rb
module ApplicationHelper
end

crm/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

crm/app/helpers/call_logs_helper.rb
module CallLogsHelper
end

crm/app/helpers/leads_helper.rb
module LeadsHelper
end

crm/app/helpers/sessions_helper.rb
module SessionsHelper
end

crm/app/helpers/users_helper.rb
module UsersHelper
end

crm/app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crm/app/views/accounts/edit.html.erb
<h1>Edit Account</h1>

<%= render 'form' %>

crm/app/views/accounts/index.html.erb
<h1>Accounts</h1>

<p> <%= link_to "New", new_account_path %>

  <% @accounts.each do |account| %>
  <div class="lead-index-container">
    <p>Name: <%= account.first_name %> <%= account.last_name %>  </p>
    <p>Phone Number: <%= account.phone_number %></p>
    <p><%= link_to 'View', account_url(account)%></p>
  </div>
  <% end %>

crm/app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

crm/app/views/accounts/show.html.erb
<h1>Accounts</h1>
<div class="lead-container">
  <div class="container1">

   First Name: <%= @account.first_name %> <br />
   Last Name: <%=@account.last_name %> <br />
   Telephone: <%=@account.phone_number %> <br />
   Notes: <%= @account.notes %> <br />
  </div>

  <div class="container2">

    <span class="sublinks"><%= link_to 'Edit', edit_account_path %> </span>
    <span class="sublinks"><%= link_to 'Delete', account_path(@account), method: :delete %> </span>
    <span class="sublinks"><%= link_to 'Back', accounts_path %> </span>

  </div>
<div>

crm/app/views/appointments/_form.html.erb
<%= form_for [@lead, @appointment] do |f| %>

<% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% f.hidden_field :lead_id, value: @lead.id %>

<div class="">
  <%= f.label :date %><br>
  <%= f.date_field :date %>
  <!-- <%= select_month DateTime.now %>
  <%= select_day DateTime.now  %>
  <%= select_year DateTime.now %> -->
</div>

<div class="">
  <%= f.label :time %><br>
  <%= f.time_field :time %>
</div>
 <br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crm/app/views/appointments/edit.html.erb
<h1 class="title">Edit Appointment</h1>

<%= link_to 'Back', lead_appointments_path(@lead) %>

<%= render 'form' %>

crm/app/views/appointments/index.html.erb
<h1 class="title">Appointments</h1>

<%= link_to 'Setup Appointment', new_lead_appointment_path(@lead,@appointment) %>
<%= link_to 'Back', lead_url(@lead) %>



<% @lead.appointments.each do |appointment| %>
  <div class="appointment-index-container">

    <p>
       <%= appointment.date.strftime("%A %B %d, %Y") %> <br />
       <%= appointment.time.strftime("%l:%M %p")%>
    </p>

  <%= link_to 'Show', lead_appointment_path(@lead,appointment) %>
  </div>
<% end %>

crm/app/views/appointments/new.html.erb
<h1 class="title"> Make an Appointment</h1>

<%= link_to 'Back', lead_appointments_path(@lead) %>

<%= form_for [@lead, @appointment] do |f| %>

<% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% f.hidden_field :lead_id, value: @lead.id %>

<div class="">
  <%= f.label :date %><br>
  <%= f.date_field :date %>
  <!-- <%= select_month DateTime.now %>
  <%= select_day DateTime.now  %>
  <%= select_year DateTime.now %> -->
</div>

<div class="">
  <%= f.label :time %><br>
  <%= f.time_field :time %>
</div>
 <br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crm/app/views/appointments/show.html.erb
<h1 class="title">Appointment Details</h1>

<h2><%= @appointment.date.strftime("%A %B %d, %Y")%></h2>
<h2><%= @appointment.time.strftime("%l:%M %p") %></h2>

<%= link_to 'Back', lead_appointments_path(@lead) %>
<%= link_to 'Edit', edit_lead_appointment_path(@lead,@appointment) %>

crm/app/views/call_logs/_form.html.erb
<%= form_for [@lead, @call_log] do |f| %>

<% if @call_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call_log.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @call_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<% f.hidden_field :lead_id, value: @lead.id %>

  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crm/app/views/call_logs/edit.html.erb
<h1 class="title">Edit</h1>


<%= render 'form' %>

<%= link_to 'Back', lead_call_logs_path(@lead) %>

crm/app/views/call_logs/index.html.erb
<h1 class="title">Call Log</h1>


<%= link_to 'Back', lead_url(@lead) %>
<%= link_to 'New Entry', new_lead_call_log_path(@lead,@call_log) %>

<h2> Call Logs </h2>

<% @lead.call_logs.each do |call_log| %>
<div class="calllog-index-container">


  <p>
     <%= call_log.created_at.strftime("%A %B %d, %Y") %>
     <%= call_log.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %p")%>
     <p> Log: <br/> <%= call_log.note %> </p>
  </p>

  <%= link_to 'View', lead_call_log_path(@lead,call_log) %>
</div>
<% end %>

crm/app/views/call_logs/new.html.erb
<h1 class="title">New</h1>

<%= render 'form' %>

  <%= link_to 'Back', lead_call_logs_path(@lead) %>

crm/app/views/call_logs/show.html.erb
<h1 class="title"><%= @call_log.created_at.strftime("%A %B %d, %Y") %></h1>

 <%= @call_log.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %p")%>

 <p> Log: <br/> <%= @call_log.note %> </p>

  <%= link_to 'Back', lead_call_logs_path(@lead) %>
  <%= link_to 'Edit', edit_lead_call_log_path(@lead,@call_log) %>

crm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>

      <h2>CRM</h2>
      <div class="header">
        <span class="header-links"><%= link_to 'Leads', leads_path %></span>
        <span class="header-links"><%= link_to 'Create Lead', new_lead_path %></span>
        <span class="header-links"><%= link_to 'Accounts', accounts_path %></span>
        <span class="header-links"><%= link_to 'Add Account', new_account_path %></span>
        <span class="header-links"><%= link_to 'Signup', new_user_path %></span>
      </div>
    </header>
  <%= yield %>

  <footer>
    <h2> &copy; 2017</h2>
  </footer>
  </body>
</html>

crm/app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

crm/app/views/leads/edit.html.erb
<h1 class="title">Edit</h1>

<%= render 'form' %>

<%= link_to 'Back', lead_url(@lead) %>

crm/app/views/leads/index.html.erb
<h1 class="lead-title">Leads</h1>



  <% @leads.each do |lead| %>
  <div class="lead-index-container">
    <p>Name: <%= lead.first_name %> <%= lead.last_name %>  </p>
    <p>Phone Number: <%= lead.phone_number %></p>
    <p><%= link_to 'View', lead_url(lead)%></p>
  </div>
  <% end %>

crm/app/views/leads/new.html.erb
<h1 class="title">New Lead</h1>

<%= link_to 'Back', leads_path %>

<%= render 'form' %>

crm/app/views/leads/show.html.erb
<h1 class="title">Lead Info</h1>
<div class="lead-container">
  <div class="container1">

   First Name: <%= @lead.first_name %> <br />
   Last Name: <%=@lead.last_name %> <br />
   Telephone: <%=@lead.phone_number %> <br />
   Notes: <%= @lead.notes %> <br />
  </div>
 <div class="container2">

   <span class="sublinks"><%= link_to 'Edit', edit_lead_path %> </span>
   <span class="sublinks"><%= link_to 'Delete', lead_path(@lead), method: :delete %> </span>
   <span class="sublinks"><%= link_to 'Back', leads_path %> </span>

   <span class="sublinks"><%= link_to 'Call Log', lead_call_logs_path(@lead) %> </span>
   <span class="sublinks"><%= link_to 'Appointments', lead_appointments_path(@lead) %> </span>

 </div>


<%= form_for @account do |f| %>

<%= f.hidden_field :first_name, value: @lead.first_name%>
<%= f.hidden_field :last_name, value: @lead.last_name%>
<%= f.hidden_field :phone_number, value: @lead.phone_number%>
<%= f.hidden_field :notes, value: @lead.notes%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

crm/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>